import React from 'react'
import Navbar from '../Layout/Navbar'
import Footer from '../Layout/Footer'

const Term_Of_Use = () => {
  return (
    <>
     <Navbar/>
     <div className="bg_autho">
        <div className="py-5">
          <h1 className="autho_title">Terms of Use</h1>
          <p className="autho_para">Create Marketing and Festivals posts with Your Business Information In Just few seconds.</p>
        </div>
      </div>
      <div className="py-5 px-3">
        <div className="info_autho">
          <span>This Privacy Policy is applicable to personally identifiable information collected, processed, stored and used in connection with http://365posts.app/ or via an dedicated application of the said URL accessible on Users’ mobile phones / tablets / other devices connected to the internet ("App") operated by 365 Posts App ("365 Posts"/ "we"/ "us"/ "our") having its office at 3rd Floor, Shyam Complex, Parivar Park, Near Mayani Chowk, Rajkot-360005, Gujarat, India. This policy is in addition to the Privacy Policy incorporated otherwise on the URL.</span>
          <hr />
          <h2>1. Ownsership Restrictions On Use</h2>
          <p>The content of the App(s) and all copyrights, patents, trademarks, service marks, trade names and all other intellectual property rights therein are owned by 365 Posts and/or its licensors or group companies and are protected by applicable Indian and international copyright and other intellectual property laws. You acknowledge, understand and agree that you shall not have, nor be entitled to claim, any rights in and to the App(s) content/ Services and/or any portion thereof. You agree not to copy, reproduce, duplicate, stream, capture, access through technology or means other than those provided on the App(s), perform, transfer, sell, resell, download, upload, archive, license to others, edit, modify, manipulate, create derivative works from or based upon (including, without limitation, mash-ups, montages, wallpapers, ringtones, greeting cards, T-shirts or other merchandise), publish, republish, post, transmit, publicly display, frame, link from or to, distribute, share, embed, translate, decompile, reverse engineer, incorporate into any hardware or software application, use for commercial purposes, or otherwise use or exploit the App(s) or any component part thereof. Any of the unauthorized uses referred to above would constitute an infringement of the copyrights and other proprietary rights of 365 Posts and/or its licensors and a violation of these Terms and may subject you to civil and/or criminal liability under applicable laws.</p>
          <h2>2. Your Responsibilities</h2>
          <p>Your rights under any one or more of the Licenses set forth above are conditioned upon your compliance with each of the following:</p>
          <h2>Children's Information</h2>
          <p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity. Festival Post does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our app, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>
          <h2>3. Disclaimer Of Warranties</h2>
          <p>YOU EXPRESSLY AGREE THAT YOUR USE OF THE APP(S) IS AT YOUR SOLE RISK. THE APP(S) (AND ANY PORTION OF THE APP(S)) IS PROVIDED “AS IS” “WITH ALL FAULTS” AND “AS AVAILABLE.” TO THE FULL EXTENT PERMITTED BY LAW, 365 Posts AND ITS AFFILIATES EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED (INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND NON-INFRINGEMENT). Neither 365 Posts nor any of its affiliates make any warranties or representations about the accuracy or completeness of content available on or through the App(s) or the content of any App, Personal Social Media or other internet or mobile resources linked to the App(s) and assume no liability or responsibility for any: (i) errors, mistakes, or inaccuracies of content; (ii) personal injury or property damage, of any nature whatsoever, resulting from your access to or use of the App(s) (or any parts thereof); (iii) any unauthorized access to or use of our secure servers and/or any and all personal information stored therein; (iv) any interruption or cessation of transmission to or from the App(s); (v) for any loss or damage of any kind incurred as a result of the use of any User Submissions and/or other App(s) content posted, shared, forwarded, emailed, transmitted, or otherwise made available on or by means of App(s) and/or otherwise through your or any other App(s) users' exercise of any rights under any of the Licenses granted by 365 Posts herein. 365 Posts reserves the right, in its sole and exclusive discretion, to change, modify, add, remove or disable access to any portion of the App(s) (including, without limitation any of the Services).</p>
          <h2>4. Indemnification</h2>
          <p>You agree to indemnify and hold harmless 365 Posts and its affiliates and its and their respective officers, directors, employees, representatives, licensees, authorized designees, successors and assigns from any and all claims, liabilities, damages, losses, costs, expenses, fees (including reasonable outside attorneys' fees and costs) that such parties may incur as a result of or arising from (i) any of your User Submissions; (ii) your exercise of any of your rights granted under the Licenses without your compliance with your responsibilities set forth in these Terms; (ii) the breach of any of your warranties, representations, covenants, responsibilities or other obligations set forth in these Terms; (iii) your violation of any person's intellectual property, privacy, publicity or other right; (iv) the violation of any Applicable Laws and/or these Terms by you and/or anyone using your registered account to access and/or otherwise use the Site (in whole or in part); or (v) your willful misconduct or the willful misconduct of anyone accessing the App through your registered account, in connection with your (and/or such other person's) use of the App (in whole or in part). 365 Posts reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will cooperate with 365 Posts in asserting any available defenses. This provision shall remain in full force and effect notwithstanding any termination of your use of the App.</p>
          <h2>5. Governing Law And Jurisdiction</h2>
          <p>The relationship between you and 365 Posts shall be governed by the laws of India without regard to its conflict of law provisions and for resolution of any dispute arising out of your use of the Services. Notwithstanding the foregoing, you agree that (i) 365 Posts has the right to bring any proceedings before any court/forum of competent jurisdiction and you irrevocably submit to the jurisdiction of such courts or forum and (ii) any proceeding brought by you shall be exclusively before the courts at Rajkot, Gujarat, India.</p>
          <h2>6.Severability; Waiver</h2>
          <p>If any provision of these Terms shall be held unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions. The failure of 365 Posts to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to the use of the App(s) or these Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred. This provision shall remain in full force and effect notwithstanding any termination of your use of the App(s).</p>
          <h2>7. Cancellation/Refund Policy</h2>
          <p>365 Posts application may not allow refunds. We have informed you with immense details before you choose subscribe button. If you have query or question, then you can contact on e-mail i.e. 365postsapp@gmail.com.</p>
          <h6>We acknowledge that all fees through 365 Posts application will be non-refundable.</h6>
          <p>However, if a transaction has been completed by you on the application and money has been debited from your card or net banking but a subscription is not delivered to you, then you can contact us on 365postsapp@gmail.com. We will be requesting you to provide your mobile number or e-mail id or your name and We shall investigate and come back to you. Within working day, we will subscribe you manually.Please make sure that prior to subscribe, read the refund policy.</p>
          <h2>8. Subscription</h2>
          <p>To be able to view certain premium content (“Premium Content”), you will be required to subscribe to any one subscription plan (“Plan”) of the 365 Posts App(s) Service viz., the plans available on the App(s) to be able to access the services which shall be entitled to full fee flexibility, solely at the discretion of 365 Posts. You may be required to subscribe to the 365 Posts App(s) Service and such subscription in a particular geographical territory that shall be valid for that territory only and shall not automatically entitle you to access your account from a different geographical territory, unless specifically permitted by 365 Posts. You will be required to re-subscribe to the 365 Posts App(s) Services in the event that you wish to use the services from a different territory other than the one from where you originally subscribed to the 365 Posts App(s) Service.</p>
          <h2>9. Availability</h2>
          <p>The availability of content(s) to view through 365 Posts App(s) Service will change from time to time at the sole discretion of 365 Posts. The quality of the display of the streaming video may vary from computer to computer, and device to device, and may be affected by a variety of factors, such as your location, the bandwidth available through and/or speed of your internet connection, and/ or quality of user’s hardware. You are responsible for all internet access charges. Please check with your internet provider for information on possible internet data usage charges.</p>
          <h2>10. Miscellaneous</h2>
          <p>The Privacy Policy (as provided on the Apps(s)), and any other documents, instructions, etc. included on the Apps(s) shall be read in conjunction with and shall form an integral part of these Terms of Use.</p>
        </div>
      </div>
     <Footer/> 
    </>
  )
}

export default Term_Of_Use
